- name: installation Message Queue
  apt:
    name: rabbitmq-server
    state: latest

- name: Openstack user add
  shell:
    rabbitmqctl add_user junemel01610 meljunego

- name: permission to configure, write, and read
  shell:
    rabbitmqctl set_permissions junemel01610  ".*" ".*" ".*"
